# Generated by Django 4.2.5 on 2023-09-29 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_atendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependente', to='clientes.clientes'),
        ),
        migrations.AlterModelTable(
            name='atendente',
            table='clientes_funcionario',
        ),
    ]
